// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQr5YWL3MR05-6lHMbBMFznKsm_fjpIRU',
    appId: '1:427653426450:web:de74635cb9199b83c897cb',
    messagingSenderId: '427653426450',
    projectId: 'test-fcm-20241',
    authDomain: 'test-fcm-20241.firebaseapp.com',
    storageBucket: 'test-fcm-20241.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB99wXeis8n-PxaLIYkHPDNPxVV0om-w1U',
    appId: '1:427653426450:android:dbcc071c57b17a0cc897cb',
    messagingSenderId: '427653426450',
    projectId: 'test-fcm-20241',
    storageBucket: 'test-fcm-20241.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7XPt-QLoFm6QfQOhxg8vCEJJSrfce2pY',
    appId: '1:427653426450:ios:fce44bb6c42dc651c897cb',
    messagingSenderId: '427653426450',
    projectId: 'test-fcm-20241',
    storageBucket: 'test-fcm-20241.appspot.com',
    iosBundleId: 'com.example.fcmFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7XPt-QLoFm6QfQOhxg8vCEJJSrfce2pY',
    appId: '1:427653426450:ios:fce44bb6c42dc651c897cb',
    messagingSenderId: '427653426450',
    projectId: 'test-fcm-20241',
    storageBucket: 'test-fcm-20241.appspot.com',
    iosBundleId: 'com.example.fcmFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQr5YWL3MR05-6lHMbBMFznKsm_fjpIRU',
    appId: '1:427653426450:web:537cb0ea50b90648c897cb',
    messagingSenderId: '427653426450',
    projectId: 'test-fcm-20241',
    authDomain: 'test-fcm-20241.firebaseapp.com',
    storageBucket: 'test-fcm-20241.appspot.com',
  );
}
